import { Feather } from '@expo/vector-icons';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { useColors } from '@/hooks/useColors';

type Coordinate = { latitude: number; longitude: number };
type Region = Coordinate & { latitudeDelta: number; longitudeDelta: number };
type LocationPin = { id: string; title: string; type: string; coordinate: Coordinate };
type CrowdPin = { id: string; kind: 'Safe' | 'Danger'; label: string; coordinate: Coordinate; time: string };
export type MapCanvasProps = { colors: ReturnType<typeof useColors>; region: Region; onRegionChange: (region: Region) => void; showUserLocation: boolean; shelters: LocationPin[]; crowdMarkers: CrowdPin[] };

export function MapCanvas({ colors, shelters, crowdMarkers }: MapCanvasProps) {
  return <View style={[styles.canvas, { backgroundColor: colors.input }]}><View style={[styles.route, styles.routeOne, { backgroundColor: colors.border }]} /><View style={[styles.route, styles.routeTwo, { backgroundColor: colors.border }]} /><View style={[styles.route, styles.routeThree, { backgroundColor: colors.border }]} /><View style={[styles.riskBlob, { backgroundColor: colors.critical + '24', borderColor: colors.critical + '55' }]} /><View style={[styles.safeBlob, { backgroundColor: colors.moderate + '24', borderColor: colors.moderate + '55' }]} /><Text style={[styles.mapLabel, { color: colors.mutedForeground }]}>OFFLINE AREA CACHE</Text><Feather name="map" size={30} color={colors.sageLight} style={styles.mapIcon} /><View style={[styles.userPin, { backgroundColor: colors.sage }]}><Feather name="navigation" size={15} color={colors.primaryForeground} /></View>{shelters.map((item, index) => <View key={item.id} style={[styles.pin, { backgroundColor: colors.sage, top: 76 + index * 55, left: 44 + index * 67 }]}><Feather name={item.type === 'Hospital' ? 'plus' : item.type === 'Shelter' ? 'home' : 'package'} size={12} color={colors.primaryForeground} /></View>)}{crowdMarkers.map((item, index) => <View key={item.id} style={[styles.pin, { backgroundColor: item.kind === 'Safe' ? colors.low : colors.critical, top: 205 + index * 35, left: 100 + index * 56 }]}><Feather name={item.kind === 'Safe' ? 'check' : 'alert-triangle'} size={12} color={colors.primaryForeground} /></View>)}</View>;
}

const styles = StyleSheet.create({ canvas: { flex: 1, position: 'relative', overflow: 'hidden' }, route: { position: 'absolute', height: 2, width: '140%', opacity: 0.65 }, routeOne: { top: 104, left: -25, transform: [{ rotate: '18deg' }] }, routeTwo: { top: 185, left: -36, transform: [{ rotate: '-24deg' }] }, routeThree: { top: 240, left: -20, transform: [{ rotate: '4deg' }] }, riskBlob: { position: 'absolute', width: 205, height: 140, borderRadius: 100, borderWidth: 1, top: 99, left: 92, transform: [{ rotate: '-15deg' }] }, safeBlob: { position: 'absolute', width: 150, height: 100, borderRadius: 70, borderWidth: 1, top: 30, left: 15, transform: [{ rotate: '20deg' }] }, mapLabel: { position: 'absolute', top: 88, left: 132, fontSize: 9, fontFamily: 'Inter_700Bold', letterSpacing: 1.1 }, mapIcon: { position: 'absolute', top: 123, left: 184 }, userPin: { position: 'absolute', top: 149, left: 184, width: 35, height: 35, borderRadius: 13, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#F8F9FA' }, pin: { position: 'absolute', width: 27, height: 27, borderRadius: 10, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#F8F9FA' } });
